/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mylist.boot;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App122101 classUnderTest = new App122101();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
